# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1a2e97334f3f17ae6cdd7d1f5ba01d12025fdf391aa12c8e81dfba7d927a5ed72ab4b83f7488b29069fdd709913ce9f6eb742aa243e46a456104c0e64b48fa52

test:
  secret_key_base: 6c6a3db60a054b4a87f4eb1513d4f82ecb6dd5ca2b10a8cce70b68547537db9cb47d68ec44ebf521738d3a10363c0265f6e106714d27a5d78648cbebf22375fe

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
